src/Entity/Students.php
<?php

namespace App\Entity;

use App\Repository\StudentsRepository;
use Doctrine\ORM\Mapping as ORM;
use App\Entity\Classe;
/**
 * @ORM\Entity(repositoryClass=StudentsRepository::class)
 */
class Students
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;
    
    /**
    * @ORM\ManyToOne(targetEntity=Classe::class)
    */
     
    private $classe;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Name;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getClasse(): ?Classe
    {
        return $this->classe;
    }

    public function setClasse(?Classe $classe): self
    {
        $this->classe = $classe;

        return $this;
    }
}

templates/pages/AdminPanel.html.twig
{% block body %}
<!--stylesheets-->
    <style>{% include 'css/panel.css' %} </style>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css">
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<!-- end stylesheets--> 

   <div class="header">
    <a href="#" id="menu-action"> </a>
    <div class="logo">
        Teacher Panel
    </div>
    </div>
<div class="sidebar">
    <ul>
        <li><a href="{{path('app_login')}}"><i class="fa fa-desktop"></i><span>Panel</span></a></li>
        <li><a href="{{path('calendrier')}}"><i class="fa fa-calendar"></i><span>Calendar</span></a></li>
        <li><a href="{{path('app_logout')}}"><i class="fas fa-sign-out-alt"></i><span>Logout</span></a></li>
    </ul>
</div>

<!-- Content -->
<div class="main">
    <div class="hipsum">
        <div class="jumbotron">
            <h1 id="hello-mr-mme">Hello, Mr/Mme {{ app.user.username }} </h1>
        </div>
        <p><b>Bienvenue Mr/Mme ,vous trouvez dans cette section la liste de vos matières + ses analyses.</b></p>

        {% for mat in matiers %}

        <table class="table table-bordered">
            <tr>
                <th> matier</th>
                <th> Analyse</th>
         </tr>
            <tr>
                <td>{{ mat.name }}</td>
                <td> <a href="{{ path('view',{'id':mat.id}) }}">View</a></td>
            </tr>
        </table>
        {% endfor %}

    </div>
</div>
    <script>
        $('#menu-action').click(function() {
            $('.sidebar').toggleClass('active');
            $('.main').toggleClass('active');
            $(this).toggleClass('active');

            if ($('.sidebar').hasClass('active')) {
                $(this).find('i').addClass('fa-close');
                $(this).find('i').removeClass('fa-bars');
            } else {
                $(this).find('i').addClass('fa-bars');
                $(this).find('i').removeClass('fa-close');
            }
        });

        // Add hover feedback on menu
        $('#menu-action').hover(function() {
            $('.sidebar').toggleClass('hovered');
        });
    </script>
   
{% endblock %}

templates/pages/Calendrier.html.twig
{%   extends 'base.html.twig' %}
{% block head %} 
<script language="JavaScript">
/*
Dynamic Calendar II (By Jason Moon at http://www.jasonmoon.net)
*/

var ns6=document.getElementById&&!document.all
var ie4=document.all

var Selected_Month;
var Selected_Year;
var Current_Date = new Date();
var Current_Month = Current_Date.getMonth();

var Days_in_Month = new Array(31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31);
var Month_Label = new Array('January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December');

var Current_Year = Current_Date.getYear();
if (Current_Year < 1000)
Current_Year+=1900


var Today = Current_Date.getDate();

function Header(Year, Month) {

   if (Month == 1) {
   Days_in_Month[1] = ((Year % 400 == 0) || ((Year % 4 == 0) && (Year % 100 !=0))) ? 29 : 28;
   }
   var Header_String = Month_Label[Month] + ' ' + Year;
   return Header_String;
}



function Make_Calendar(Year, Month) {
   var First_Date = new Date(Year, Month, 1);
   var Heading = Header(Year, Month);
   var First_Day = First_Date.getDay() + 1;
   if (((Days_in_Month[Month] == 31) && (First_Day >= 6)) ||
       ((Days_in_Month[Month] == 30) && (First_Day == 7))) {
      var Rows = 6;
   }
   else if ((Days_in_Month[Month] == 28) && (First_Day == 1)) {
      var Rows = 4;
   }
   else {
      var Rows = 5;
   }

   var HTML_String = '<table><tr><td valign="top"><table BORDER=4 CELLSPACING=1 cellpadding=2 FRAME="box" BGCOLOR="C0C0C0" BORDERCOLORLIGHT="808080">';

   HTML_String += '<tr><th colspan=7 BGCOLOR="FFFFFF" BORDERCOLOR="000000">' + Heading + '</font></th></tr>';

   HTML_String += '<tr><th ALIGN="CENTER" BGCOLOR="FFFFFF" BORDERCOLOR="000000">Sun</th><th ALIGN="CENTER" BGCOLOR="FFFFFF" BORDERCOLOR="000000">Mon</th><th ALIGN="CENTER" BGCOLOR="FFFFFF" BORDERCOLOR="000000">Tue</th><th ALIGN="CENTER" BGCOLOR="FFFFFF" BORDERCOLOR="000000">Wed</th>';

   HTML_String += '<th ALIGN="CENTER" BGCOLOR="FFFFFF" BORDERCOLOR="000000">Thu</th><th ALIGN="CENTER" BGCOLOR="FFFFFF" BORDERCOLOR="000000">Fri</th><th ALIGN="CENTER" BGCOLOR="FFFFFF" BORDERCOLOR="000000">Sat</th></tr>';

   var Day_Counter = 1;
   var Loop_Counter = 1;
   for (var j = 1; j <= Rows; j++) {
      HTML_String += '<tr ALIGN="left" VALIGN="top">';
      for (var i = 1; i < 8; i++) {
         if ((Loop_Counter >= First_Day) && (Day_Counter <= Days_in_Month[Month])) {
            if ((Day_Counter == Today) && (Year == Current_Year) && (Month == Current_Month)) {
               HTML_String += '<td BGCOLOR="FFFFFF" BORDERCOLOR="000000"><strong><font color="red">' + Day_Counter + '</font></strong></td>';
            }
            else {
               HTML_String += '<td BGCOLOR="FFFFFF" BORDERCOLOR="000000">' + Day_Counter + '</td>';
            }
            Day_Counter++;    
         }
         else {
            HTML_String += '<td BORDERCOLOR="C0C0C0"> </td>';
         }
         Loop_Counter++;
      }
      HTML_String += '</tr>';
   }
   HTML_String += '</table></td></tr></table>';
   cross_el=ns6? document.getElementById("Calendar") : document.all.Calendar
   cross_el.innerHTML = HTML_String;
}


function Check_Nums() {
   if ((event.keyCode < 48) || (event.keyCode > 57)) {
      return false;
   }
}



function On_Year() {
   var Year = document.when.year.value;
   if (Year.length == 4) {
      Selected_Month = document.when.month.selectedIndex;
      Selected_Year = Year;
      Make_Calendar(Selected_Year, Selected_Month);
   }
}

function On_Month() {
   var Year = document.when.year.value;
   if (Year.length == 4) {
      Selected_Month = document.when.month.selectedIndex;
      Selected_Year = Year;
      Make_Calendar(Selected_Year, Selected_Month);
   }
   else {
      alert('Please enter a valid year.');
      document.when.year.focus();
   }
}


function Defaults() {
   if (!ie4&&!ns6)
   return;
   var Mid_Screen = Math.round(document.body.clientWidth / 2);
   document.when.month.selectedIndex = Current_Month;
   document.when.year.value = Current_Year;
   Selected_Month = Current_Month;
   Selected_Year = Current_Year;
   Make_Calendar(Current_Year, Current_Month);
}


function Skip(Direction) {
   if (Direction == '+') {
      if (Selected_Month == 11) {
         Selected_Month = 0;
         Selected_Year++;
      }
      else {
         Selected_Month++;
      }
   }
   else {
      if (Selected_Month == 0) {
         Selected_Month = 11;
         Selected_Year--;
      }
      else {
         Selected_Month--;
      }
   }
   Make_Calendar(Selected_Year, Selected_Month);
   document.when.month.selectedIndex = Selected_Month;
   document.when.year.value = Selected_Year;
}

</script>
{% endblock %}

{% block body %}
<!-- menu bar -->
<style>{% include 'css/panel.css' %}</style>
<div class="header">
    <a href="#" id="menu-action">
        <i class="fa fa-bars"></i>
        <span>List</span>
    </a>
    <div class="logo">
        Teacher Panel
    </div>
</div>
<div class="sidebar">
    <ul>
        <li><a href="{{path('app_login')}}"><i class="fa fa-desktop"></i><span>Panel</span></a></li>
        <li><a href="{{path('calendrier')}}"><i class="fa fa-calendar"></i><span>Calendar</span></a></li>
        <li><a href="{{path('app_logout')}}"><i class="fas fa-sign-out-alt"></i><span>Logout</span></a></li>
    </ul>
</div>
<!-- End menu bar -->
<!--  Calendrier -->
<body onLoad="Defaults()" id="calendar">


<div  style="position:relative;width:286px;top:5px;" align="left">
<form name="when"><table >
<tr>
   <td><input type="button" value="<-- Last" onClick="Skip('-')"></td>
   <td> </td>
   <td><select name="month" onChange="On_Month()">

<script language="JavaScript1.2">
if (ie4||ns6){
   for (j=0;j<Month_Label.length;j++) {
      document.writeln('<option value=' + j + '>' + Month_Label[j]);
   }
}
</script> </select>
   </td>
   <td><input type="text" name="year" size=4 maxlength=4 onKeyPress="return Check_Nums()" onKeyUp="On_Year()"></td>
   <td> </td>
   <td><input type="button" value="Next -->" onClick="Skip('+')"></td>
</tr></table></form></div>
<br><br>
<div id=Calendar style="position:relative;width:238px;top:-2px;" align="left"></div> 
</body>
{% endblock %}
    

templates/pages/admin.html.twig
{% extends 'base.html.twig' %}
{% block body %}
<!-- inclusion du fichier css dans ma page twig -->
<style>{% include 'css/admin.css' %}</style>
<div class="row no-gutter">
        <!-- The image half -->
        <div class="col-md-6 d-none d-md-flex bg-image">
        
        </div>


        <!-- The content half -->
        <div class="col-md-6 bg-light">
            <div class="login d-flex align-items-center py-5">

                <!-- second half content-->
                
                <div class="container">
                    <div class="row">
                        <div class="col-lg-10 col-xl-7 mx-auto">
                            <h3 class="display-4">Espace Login!</h3>
                            <p class="text-muted mb-4">accée exclusive avec identificateur et mot de passe
                                pour <b>les étudiants</b> ou <b>les enseignants</b> </p>

                            <!-- sign up succes message -->
                            {% for message in app.flashes('success') %}
                                <div class="alert alert-success">
                                    {{ message }}
                                </div>
                            {% endfor %}
                            <!-- End sign up succes messafe -->

                            <form action="{{ path('app_login') }}" method="POST">
                            
                            {% if error %}
                              <div class="alert alert-danger">{{ error.messageKey|trans(error.messageData, 'security') }}</div>
                                {% endif %} -
                              
                             {% if app.user %}
                                     <div class="mb-3">
                                    You are logged in as {{ app.user.username }}, <a href="{{ path('app_logout') }}">Logout</a>
                                      </div>
                                    {% endif %} 
                                <div class="form-group mb-3">
                                    <input id="inputEmail" type="login" placeholder="login" name="username" value="{{ last_username }}" class="form-control rounded-pill border-0 shadow-sm px-4">
                                </div>
                                <div class="form-group mb-3">
                                    <input id="inputPassword" type="password" placeholder="Password" name="password" class="form-control rounded-pill border-0 shadow-sm px-4 text-primary">
                                </div>
                                <!--<div class="custom-control custom-checkbox mb-3">
                                    <input id="customCheck1" type="checkbox" checked class="custom-control-input">
                                    <label for="customCheck1" class="custom-control-label">Remember password</label>
                                </div> -->
                                
                                <button type="submit" class="btn btn-primary btn-block text-uppercase mb-2 rounded-pill shadow-sm">Sign in</button>
                                <div id="redirect_login"> <h6 style="color:green;">tu es un étudiant et vous n'avez pas inscris?<a href="{{ path('app_register') }}">inscrire ici</a></h6></div>
                                <div class="text-center d-flex justify-content-between mt-4"><p>Snippet by <a href="https://bootstrapious.com/snippets" class="font-italic text-muted"> 
                                        <u>Boostrapious</u></a></p></div>

                            </form>
                        </div>
                    </div>
                </div><!-- End -->

            </div>
        </div><!-- End -->

    </div>
</div>


{% endblock %}
{% block title %} login {% endblock %}

templates/pages/annescolaire.html.twig
{% block body %}
<!--stylesheets-->
    <style>{% include 'css/panel.css' %} </style>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css">
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<!-- end stylesheets--> 

   <div class="header">
    <a href="#" id="menu-action"> </a>
    <div class="logo">
        Teacher Panel
    </div>
    </div>
<div class="sidebar">
    <ul>
        <li><a href="{{path('app_login')}}"><i class="fa fa-desktop"></i><span>Panel</span></a></li>
        <li><a href="{{path('calendrier')}}"><i class="fa fa-calendar"></i><span>Calendar</span></a></li>
        <li><a href="{{path('app_logout')}}"><i class="fas fa-sign-out-alt"></i><span>Logout</span></a></li>
    </ul>
</div>

<!-- Content -->
<div class="main">
    <div class="hipsum">
        <div class="jumbotron">
            <h1 id="hello-mr-mme">Hello, Mr/Mme {{ app.user.username }} </h1>
        </div>
        <p><b>Bienvenue Mr/Mme ,veuiller choisir l'année et semestre convenable.</b></p>
    <div class="row">
{#        <div class="col-one">#}
{#            <h1 class="heading">Media cards</h1>#}
{#        </div>#}
    </div>
    <div class="row" style="padding-left: 20px;padding-right: 20px">
        {% for key,val in annees  %}

    <div class="col-thirds">
        <div class="media-card">
            <div class="media-card-image-wrapper">
                <img src="https://1.bp.blogspot.com/-W50kEL-64d8/YNTkVp1_iWI/AAAAAAAACHM/iWPSvH2ZUIQeP26rz9f97ly2xXowcqAeACLcBGAsYHQ/s0/ann%25C3%25A9e.jpg" alt="">
                <div class="media-card-meta-taxonomy">
                    Année Scolaire
                </div>
            </div>
            <div class="media-card-title">
                <h2>{{key}}</h2>
                <div class="media-card-meta-date">
                    {% if val[0].courante == 1 %}
                    Courante
                    {% endif %}
                </div>
            </div>
            <div class="media-card-content">
                <div class="row">
                    <div class="col-6">
                    <div class="semestreStyle" style="text-align: center">
                        <a href="{{ path('adminpanel',{'id':id , 'semestre': val[0].id}) }}" style="color: white">
                            Semestre 1
                        </a>
                    </div>
                    </div>
                    <div class="col-6">
                    <div class="semestreStyle" style="text-align: center">
                        <a href="{{ path('adminpanel',{'id':id , 'semestre': val[1].id}) }}" style="color: white">
                            Semestre 2
                        </a>
                    </div>
                    </div>
                </div>

            </div>
            <div class="media-card-button">
                <a href="#"></a>
            </div>
        </div>
    </div>
        {% endfor %}
    </div>
    </div>
</div>
        <!-- main container -->

    <script>
        $('#menu-action').click(function() {
            $('.sidebar').toggleClass('active');
            $('.main').toggleClass('active');
            $(this).toggleClass('active');

            if ($('.sidebar').hasClass('active')) {
                $(this).find('i').addClass('fa-close');
                $(this).find('i').removeClass('fa-bars');
            } else {
                $(this).find('i').addClass('fa-bars');
                $(this).find('i').removeClass('fa-close');
            }
        });

        // Add hover feedback on menu
        $('#menu-action').hover(function() {
            $('.sidebar').toggleClass('hovered');
        });
    </script>

{% endblock %}

templates/pages/apropos.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<!-- inclusion du fichier css dans ma page twig -->
<style>{% include 'css/Apropos.css' %}</style>
<div class="description">
<br>
<h2> Evaluation.edu </h2>
<h3> A propos </h3>
    <p>  une application web  pour mener des enquêtes  a de retour un  analyse pour les avis  des étudiants
             sur les qualités des cours et le système d'éducation </p>
             <ul>
             <li> L’application offre l’opportunité aux étudiants d’évaluer leurs perceptions des cours.  
             <li> Les étudiants répondent à des questions bien définies   en attribuant des (*) Etoiles de 1 à 5 suivants leurs degrés d’assimilations.</li>
             <li> <b>&#8594;</b>L’objectif est de construire des enquêtes avec des indicateurs mesurable et informer les instructeurs du cours de celle-ci</li>
             <li> Les réponses aux enquêtes seront anonymes et les statistiques de perceptions des cours seront calculés pour les cours.
             </li>
             <li>  Un bilan statistique sur les réponses sera envoyé sous forme de rapport d’évaluation aux enseignants concernés.
             Les enseignants doit connecté avec un login et mot de passe pour voir les analyses.
             </li>
             </ul>
</div>

{% endblock %}
{% block title %} A propos{% endblock %}

templates/pages/qcm.html.twig
{% extends 'base.html.twig' %}
{% block head %}
<!-- import font awesome v4 icons -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
{% endblock %}
{% block body %}
<!-- inclusion du fichier css dans ma page twig -->
<style>{% include 'css/qcm.css' %}</style>
<style>

        .rating {
                display: block;
                direction: rtl;
                unicode-bidi: bidi-override;
                text-align: center;
        }
        .rating .star {
                display: none;
        }
        .rating label {
                color: #ffffff;
                display: inline-block;
                font-size: 22pt;
                margin: 0 -2px;
                transition: transform .15s ease;
        }
        .rating label:hover {
                transform: scale(1.35, 1.35);
        }
        .rating label:hover,
        .rating label:hover ~ label {
                color: orange;
        }
        .rating .star:checked ~ label {
                color: orange;
        }
        #exit{
            margin-left:91%;
        }
        #exit-text{
            font-size:23px;
            color:blue;
        }
</style>
<div id="exit">
    <a href="{{ path('app_logout') }}" id="exit-text">

        <img src="https://1.bp.blogspot.com/-FBSLE4k4wEA/YOiJybRPb6I/AAAAAAAACM8/UsRzXHirAtgb954Cti1KHxdkVjSvJeAxwCLcBGAsYHQ/s0/exit.png"
             width="54px" height="54px"> exit
    </a>
</div>
<!-- source des questions : 
https://www.reptic.qc.ca/wp-content/uploads/2014/05/2014-05_STFO_questionnaire-evaluation-formative.pdf -->
<div class="qcm-body">
        matière: {{ matiere.name }}
<form method="post" id="form" action="{{ path('save_qcm',{'id': id , 'stu': stu}) }}">
    {% for key, val in qcms %}
            
        <h2 id="sujet"> {{key}} </h2>
            {% for qcm in val %}
        <h5 style="font-size:16px" id="titre"> {{ qcm.question.titre }} :</h5>

                    <div class="rating">
                            <input id="radio1{{ qcm.question.id }}" type="checkbox" name="{{ qcm.question.id }}qes[]" {% if qcm.note == 5 %} checked="checked" {% endif %} value="5" class="star" />
                            <label for="radio1{{ qcm.question.id }}">&#9733;</label>
                            <input id="radio2{{ qcm.question.id }}" type="checkbox" name="{{ qcm.question.id }}qes[]" {% if qcm.note == 4 %} checked="checked" {% endif %}  value="4" class="star" />
                            <label for="radio2{{ qcm.question.id }}">&#9733;</label>
                            <input id="radio3{{ qcm.question.id }}" type="checkbox" name="{{ qcm.question.id }}qes[]" {% if qcm.note == 3 %} checked="checked" {% endif %}  value="3" class="star" />
                            <label for="radio3{{ qcm.question.id }}">&#9733;</label>
                            <input id="radio4{{ qcm.question.id }}" type="checkbox" name="{{ qcm.question.id }}qes[]" {% if qcm.note == 2 %} checked="checked" {% endif %}  value="2" class="star" />
                            <label for="radio4{{ qcm.question.id }}">&#9733;</label>
                            <input id="radio5{{ qcm.question.id }}" type="checkbox" name="{{ qcm.question.id }}qes[]" {% if qcm.note == 1 %} checked="checked" {% endif %}  value="1" class="star" />
                            <label for="radio5{{ qcm.question.id }}">&#9733;</label>
                    </div>
                    <br>

            {% endfor %}
            {% endfor %}
        <!-- desactiver bouton enregistrer des réponses -->
        {% for val in qcms %}
                {% for qcm in val %}
                        {% if qcm.note != "1" %}
                                {%set i = i+1 %}
                        {% endif %}
                {% endfor %}
        {% endfor %}

        <input type="submit" class="myButton" {% if i > 0 %} disabled {% endif %} value="Enregistrer"> </input>

        <!-- desactiver bouton enregistrer des réponses -->
</form>
</div>

<script>
        $('.star').on('change', function() {
                let stars = $(this).val();
                /* Make an AJAX call to register the rating */
                console.log(stars);
        });
</script>
{% endblock %}
{% block title %} questionnaire {% endblock %}

templates/pages/qcmlist.html.twig
{% extends 'base.html.twig' %}
{% block body %}
<!-- inclusion du fichier css dans ma page twig -->
<style>{% include 'css/qcmlist.css' %}</style>
<div id="exit">
    <a href="{{ path('app_logout') }}" id="exit-text">

    <img src="https://1.bp.blogspot.com/-FBSLE4k4wEA/YOiJybRPb6I/AAAAAAAACM8/UsRzXHirAtgb954Cti1KHxdkVjSvJeAxwCLcBGAsYHQ/s0/exit.png"
         width="60px" height="60px"> exit
    </a>

</div>
<div class="containerEnq">
    <h4>Bienvenue {{ studient.username }}</h4>
    <h5>Liste de matières pour la classe : {{ classe.name }}</h5>
</div>
<table class="table">
 <thead class="thead-light">
    <tr>
      <th scope="col">Matière</th>
      <th scope="col">QCM</th> 
    </tr>
    </thead>
{% for key,val in matieres %}
<tbody>
<tr>
<td id="semestre">  {{ key }} </td> <td id="semestre"> <a href="" value="qcm"></a></td>
</tr>
    {% for matiere in val %}
<tr>
<td id="matiere-font"> {{ matiere.name }} </td> <td id="qcm-link"> <a href="{{ path('qcm',{'id': matiere.id, 'idstudent': studient.id}) }}" value="qcm"> QCM </a></td>
</tr>
{% endfor %}

</tbody>
{% endfor %}
</table>

{% endblock %}
{% block title %} List QCM {% endblock %}

templates/pages/statistiqueprof.html.twig
{% extends 'base.html.twig' %}
{% block head %}
<!-- import font awesome v4 icons -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">


{% endblock %}
{% block body %}
<!-- inclusion du fichier css dans ma page twig -->
<style>{% include 'css/qcm.css' %}</style>
<style>

        .rating {
                display: block;
                direction: rtl;
                unicode-bidi: bidi-override;
                text-align: center;
        }
        .rating .star {
                display: none;
        }
        .rating label {
                color: lightgray;
                display: inline-block;
                font-size: 22pt;
                margin: 0 -2px;
                transition: transform .15s ease;
        }
        .rating label:hover {
                transform: scale(1.35, 1.35);
        }
        .rating label:hover,
        .rating label:hover ~ label {
                color: orange;
        }
        .rating .star:checked ~ label {
                color: orange;
        }
        .progress{
                border:2px solid #121169;
                margin-left:15%;
                margin-right:15%;
        }
        #info{
                font-size:17px;
        }
        #exit{
                margin-left:91%;
        }
        #exit-text{
                font-size:23px;
                color:blue;
        }
</style>
        <div id="exit">
                <a href="{{ path('app_logout') }}" id="exit-text">

                        <img src="https://1.bp.blogspot.com/-FBSLE4k4wEA/YOiJybRPb6I/AAAAAAAACM8/UsRzXHirAtgb954Cti1KHxdkVjSvJeAxwCLcBGAsYHQ/s0/exit.png"
                             width="54px" height="54px"> exit
                </a>
        </div>
<!-- source des questions : 
https://www.reptic.qc.ca/wp-content/uploads/2014/05/2014-05_STFO_questionnaire-evaluation-formative.pdf -->
        <div class="qcm-body" onload="window.print()">
                <i id="info"> Matière: {{ matiere.name }} </i> <br>
                <i id="info"> Groupe:  {{ classe.name }} </i> <br>
                <i id="info"> Période: {{ periode.semestre }}</i>
                <form method="post" action="">
                        {% for key, val in questions %}
                                {#                                        {% for nb in nombre_reponses %}#}
                                <h2 id="sujet"> {{ key }} </h2>
                                {% for qcm in val %}
                                        <h4 style="font-size:16px" id="titre">  {{ qcm.titre }} : </h4>
                                        {% for k,v in result %}
                                                {% if k == qcm.id %}
                                                        <div class="rating">
                                                                <label style="color:black;"> taux de satisfaction </label>
                                                                <div class="progress">

                                                                        <div class="progress-bar" role="progressbar"
                                                                             style="width: {{ 100-v*20 }}%; text-align:left;background-color:rgba(18,17,105,0.6);color:rgb(255,153,9);font-family: 'Arial Black'"
                                                                             aria-valuenow="{{ v*20 }}"
                                                                             aria-valuemin="0"
                                                                                {#round () un seul entier aprés le virgule#}
                                                                             aria-valuemax="100">{{ v*20 }}%
                                                                        </div>
                                                                </div>
                                                                <p style="color:black;" for="{{ qcm.id }}"> nombre des étudiants inscris dans le système
                                                                        : {{ nombre_reponses/24 }}</p>

                                                        </div>
                                                {% endif %}
                                        {% endfor %}
                                {% endfor %}
                        {% endfor %}
<input type="button" class="myButton" value="imprimer" onclick="window.print();" />
</form>
</div>
<script>
        $('.star').on('change', function() {
                let stars = $(this).val();
                /* Make an AJAX call to register the rating */
                console.log(stars);
        });
</script>

{% endblock %}
{% block title %} questionnaire {% endblock %}